package util

const GetDataFail = "数据获取失败"
const GetDataSuccess = "数据获取成功"
const LoginFail = "登陆失败"
const LoginSuccess = "登陆成功"
const RegisterSuccess = "注册成功"
const RegisterFail = "注册失败"
const InfoFail = "修改用户信息失败"
const InfoSuccess = "修改用户信息成功"
const PasswordSuccess = "修改用户密码成功"
const PasswordFail = "修改用户密码失败"
const ComplainRepairSuccess = "投诉报修成功"
const ComplainRepairFail = "投诉报修失败"
const RecommendNoticeSuccess = "获取推荐公告成功"
const RecommendNoticeFail = "获取推荐公告失败"
const DetailNoticeSuccess = "获取公告详细信息成功"
const DetailNoticeFail = "获取公告详细信息失败"
const PublishNoticeSuccess = "公告发布成功"
const PublishNoticeFail = "公告发布失败"
const RequestFail = "请求失败"
const RequestSuccess = "请求成功"
const PropertyFail = "物业费缴纳失败"
const PropertySuccess = "物业费缴纳成功"
