// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "zwy"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/cr": {
            "get": {
                "description": "获取全部的投诉报修信息",
                "tags": [
                    "管理员模块"
                ],
                "summary": "getAllComplainRepair",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    }
                }
            }
        },
        "/admin/login": {
            "get": {
                "description": "管理员登录",
                "tags": [
                    "管理员模块"
                ],
                "summary": "adminLogin",
                "parameters": [
                    {
                        "type": "string",
                        "description": "管理员账号",
                        "name": "username",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "管理员密码",
                        "name": "password",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    }
                }
            }
        },
        "/admin/notice": {
            "get": {
                "description": "获取全部社区公告信息",
                "tags": [
                    "管理员模块"
                ],
                "summary": "getAllNotice",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    }
                }
            }
        },
        "/houserentsale": {
            "get": {
                "description": "根据ID删除房屋",
                "tags": [
                    "房屋租售模块"
                ],
                "summary": "DeleteHouseRentSale",
                "parameters": [
                    {
                        "type": "string",
                        "description": "房屋主键ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    }
                }
            }
        },
        "/houserentsale/all": {
            "get": {
                "description": "获取全部的房屋信息",
                "tags": [
                    "房屋租售模块"
                ],
                "summary": "RentSale",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    }
                }
            }
        },
        "/houserentsale/rent": {
            "get": {
                "description": "获取全部租房信息",
                "tags": [
                    "房屋租售模块"
                ],
                "summary": "Rent",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    }
                }
            }
        },
        "/houserentsale/sale": {
            "get": {
                "description": "获取全部的售房信息",
                "tags": [
                    "房屋租售模块"
                ],
                "summary": "Sale",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    }
                }
            }
        },
        "/notice/delete": {
            "get": {
                "description": "删除公告根据标题",
                "tags": [
                    "社区公告模块"
                ],
                "summary": "deleteNotice",
                "parameters": [
                    {
                        "type": "string",
                        "description": "公告标题",
                        "name": "title",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    }
                }
            }
        },
        "/notice/detail": {
            "get": {
                "description": "获取公告的详细信息",
                "tags": [
                    "社区公告模块"
                ],
                "summary": "detailNotice",
                "parameters": [
                    {
                        "type": "string",
                        "description": "公告标题",
                        "name": "title",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    }
                }
            }
        },
        "/notice/publish": {
            "post": {
                "description": "发布社区公告",
                "tags": [
                    "社区公告模块"
                ],
                "summary": "publishNotice",
                "parameters": [
                    {
                        "description": "Notice结构体",
                        "name": "notice",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Notice"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    }
                }
            }
        },
        "/notice/recommend": {
            "get": {
                "description": "获取推荐公告，按发布时间最新排序",
                "tags": [
                    "社区公告模块"
                ],
                "summary": "recommendNotice",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    }
                }
            }
        },
        "/property/get": {
            "get": {
                "description": "获取物业费",
                "tags": [
                    "物业费模块"
                ],
                "summary": "getProperty",
                "parameters": [
                    {
                        "type": "string",
                        "description": "房屋ID",
                        "name": "houseId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    }
                }
            }
        },
        "/property/pay": {
            "get": {
                "description": "缴纳物业费",
                "tags": [
                    "物业费模块"
                ],
                "summary": "payProperty",
                "parameters": [
                    {
                        "type": "string",
                        "description": "房屋ID",
                        "name": "houseId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "缴纳金额",
                        "name": "property",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    }
                }
            }
        },
        "/tsbx/add": {
            "post": {
                "description": "添加投诉报修",
                "tags": [
                    "投诉报修模块"
                ],
                "summary": "addComplainRepair",
                "parameters": [
                    {
                        "description": "TSBX结构体",
                        "name": "tb",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.TSBX"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    }
                }
            }
        },
        "/tsbx/all": {
            "get": {
                "description": "后天管理员获取全部的投诉报修",
                "tags": [
                    "投诉报修模块"
                ],
                "summary": "GetAllComplainRepair",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    }
                }
            }
        },
        "/tsbx/get": {
            "get": {
                "description": "获取本人的投诉报修",
                "tags": [
                    "投诉报修模块"
                ],
                "summary": "getComplainRepairByUsername",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户账号",
                        "name": "username",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    }
                }
            }
        },
        "/user/get": {
            "get": {
                "description": "获取用户信息根据username",
                "tags": [
                    "用户模块"
                ],
                "summary": "getUserInfo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户账户",
                        "name": "username",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    }
                }
            }
        },
        "/user/info": {
            "post": {
                "description": "修改用户信息",
                "tags": [
                    "用户模块"
                ],
                "summary": "editUserInfo",
                "parameters": [
                    {
                        "description": "User结构体包含要修改的字段",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "get": {
                "description": "用户使用账户和密码登录",
                "tags": [
                    "用户模块"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户账户",
                        "name": "username",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户密码",
                        "name": "password",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    }
                }
            }
        },
        "/user/password": {
            "post": {
                "description": "修改用户密码",
                "tags": [
                    "用户模块"
                ],
                "summary": "editUserPassword",
                "parameters": [
                    {
                        "description": "User结构体只包含username和password",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    }
                }
            }
        },
        "/user/register": {
            "get": {
                "description": "用户输入在账号，密码，并绑定自己的房屋ID，昵称",
                "tags": [
                    "用户模块"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户账户",
                        "name": "username",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户密码",
                        "name": "password",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户昵称",
                        "name": "nickname",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "房屋ID",
                        "name": "houseId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/util.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Notice": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "公告内容",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "publish_time": {
                    "description": "公告发布时间",
                    "type": "string"
                },
                "publisher": {
                    "description": "公告发布者",
                    "type": "string"
                },
                "title": {
                    "description": "公告发布标题",
                    "type": "string"
                }
            }
        },
        "model.TSBX": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "cr_type": {
                    "description": "投诉 报修",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "status": {
                    "description": "未处理 处理中 已处理",
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.User": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "house_id": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "util.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "object"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "社区便民服务接口",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
